In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('Bird_Strikes_Final.csv')

In [7]:
df.head()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
0,202152,Airplane,LAGUARDIA NY,> 1000 ft,B-737-400,Over 100,859,Engine Shut Down,11/23/00 0:00,Caused damage,...,False,FLT 753. PILOT REPTD A HUNDRED BIRDS ON UNKN T...,Medium,No Cloud,Unknown bird - medium,N,"30,736","1,500",0,Yes
1,208159,Airplane,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,MD-80,Over 100,424,None,7/25/01 0:00,Caused damage,...,False,102 CARCASSES FOUND. 1 LDG LIGHT ON NOSE GEAR ...,Small,Some Cloud,Rock pigeon,Y,0,0,0,No
2,207601,Airplane,LAKEFRONT AIRPORT,< 1000 ft,C-500,Over 100,261,None,9/14/01 0:00,No damage,...,False,FLEW UNDER A VERY LARGE FLOCK OF BIRDS OVER AP...,Small,No Cloud,European starling,N,0,50,0,No
3,215953,Airplane,SEATTLE-TACOMA INTL,< 1000 ft,B-737-400,Over 100,806,Precautionary Landing,9/5/02 0:00,No damage,...,False,"NOTAM WARNING. 26 BIRDS HIT THE A/C, FORCING A...",Small,Some Cloud,European starling,Y,0,50,0,Yes
4,219878,Airplane,NORFOLK INTL,< 1000 ft,CL-RJ100/200,Over 100,942,None,6/23/03 0:00,No damage,...,False,NO DMG REPTD.,Small,No Cloud,European starling,N,0,50,0,No

In [8]:
df.tail()

,Record ID,Aircraft: Type,Airport: Name,Altitude bin,Aircraft: Make/Model,Wildlife: Number struck,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,...,Remains of wildlife sent to Smithsonian,Remarks,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Cost: Total $,Feet above ground,Number of people injured,Is Aircraft Large?
25553,321151,Airplane,REDDING MUNICIPAL,> 1000 ft,EMB-120,1,1,None,12/30/11 0:00,No damage,...,False,DUCK? NO DMG REPTD.,Large,Overcast,Unknown bird - large,N,0,"1,500",0,No
25554,319677,Airplane,ORLANDO INTL,< 1000 ft,A-321,1,1,None,12/30/11 0:00,No damage,...,False,NaN,Small,Some Cloud,Tree swallow,Y,0,0,0,No
25555,319680,NaN,NaN,NaN,EC-135,NaN,1,NaN,NaN,No damage,...,False,STRUCK BIRD ON RT FRONT DURING T/O. BIRD REPTD...,NaN,No Cloud,Unknown bird - small,NaN,0,NaN,0,NaN
25556,319679,Airplane,DETROIT METRO WAYNE COUNTY ARPT,< 1000 ft,B-757-200,1,1,None,12/31/11 0:00,No damage,...,False,PILOTS REPORT STRIKING UNKNOWN BIRD ON RWY 21L...,Medium,Some Cloud,Unknown bird - medium,Y,0,0,0,Yes
25557,319593,Airplane,ABRAHAM LINCOLN CAPITAL ARPT,< 1000 ft,B-737-400,1,1,None,12/31/11 0:00,Caused damage,...,False,"HIT CENTER OF RADOME, CAVING IN ABOUT 12"". RAD...",Medium,No Cloud,Red-tailed hawk,N,0,0,0,Yes

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Record ID                                25558 non-null  int64
 1   Aircraft: Type                           25429 non-null  object
 2   Airport: Name                            25429 non-null  object
 3   Altitude bin                             25429 non-null  object
 4   Aircraft: Make/Model                     25558 non-null  object
 5   Wildlife: Number struck                  25429 non-null  object
 6   Wildlife: Number Struck Actual           25558 non-null  int64
 7   Effect: Impact to flight                 25429 non-null  object
 8   FlightDate                               25429 non-null  object
 9   Effect: Indicated Damage                 25558 non-null  object
 10  Aircraft: Number of engines?             25291 non-null  object
 11  Aircraft: Airline/Operator               25429 non-null  object
 12  Origin State                             25109 non-null  object
 13  When: Phase of flight                    25429 non-null  object
 14  Conditions: Precipitation                25558 non-null  object
 15  Remains of wildlife collected?           25558 non-null  bool
 16  Remains of wildlife sent to Smithsonian  25558 non-null  bool
 17  Remarks                                  20787 non-null  object
 18  Wildlife: Size                           25429 non-null  object
 19  Conditions: Sky                          25558 non-null  object
 20  Wildlife: Species                        25558 non-null  object
 21  Pilot warned of birds or wildlife?       25429 non-null  object
 22  Cost: Total $                            25558 non-null  object
 23  Feet above ground                        25429 non-null  object
 24  Number of people injured                 25558 non-null  int64
 25  Is Aircraft Large?                       25429 non-null  object
dtypes: bool(2), int64(3), object(21)
memory usage: 4.7+ MB

In [10]:
df.isnull().sum()

Record ID                                     0
Aircraft: Type                              129
Airport: Name                               129
Altitude bin                                129
Aircraft: Make/Model                          0
Wildlife: Number struck                     129
Wildlife: Number Struck Actual                0
Effect: Impact to flight                    129
FlightDate                                  129
Effect: Indicated Damage                      0
Aircraft: Number of engines?                267
Aircraft: Airline/Operator                  129
Origin State                                449
When: Phase of flight                       129
Conditions: Precipitation                     0
Remains of wildlife collected?                0
Remains of wildlife sent to Smithsonian       0
Remarks                                    4771
Wildlife: Size                              129
Conditions: Sky                               0
Wildlife: Species                             0
Pilot warned of birds or wildlife?          129
Cost: Total $                                 0
Feet above ground                           129
Number of people injured                      0
Is Aircraft Large?                          129
dtype: int64

In [11]:
df1 = df[['Airport: Name','Altitude bin','Wildlife: Number Struck Actual','Effect: Impact to flight','FlightDate',
          'Effect: Indicated Damage','Aircraft: Airline/Operator','Origin State','When: Phase of flight',
         'Wildlife: Size','Conditions: Sky','Wildlife: Species','Pilot warned of birds or wildlife?',
          'Feet above ground',]]  # Data selection

In [12]:
df1.head()

,Airport: Name,Altitude bin,Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Feet above ground
0,LAGUARDIA NY,> 1000 ft,859,Engine Shut Down,11/23/00 0:00,Caused damage,US AIRWAYS*,New York,Climb,Medium,No Cloud,Unknown bird - medium,N,"1,500"
1,DALLAS/FORT WORTH INTL ARPT,< 1000 ft,424,None,7/25/01 0:00,Caused damage,AMERICAN AIRLINES,Texas,Landing Roll,Small,Some Cloud,Rock pigeon,Y,0
2,LAKEFRONT AIRPORT,< 1000 ft,261,None,9/14/01 0:00,No damage,BUSINESS,Louisiana,Approach,Small,No Cloud,European starling,N,50
3,SEATTLE-TACOMA INTL,< 1000 ft,806,Precautionary Landing,9/5/02 0:00,No damage,ALASKA AIRLINES,Washington,Climb,Small,Some Cloud,European starling,Y,50
4,NORFOLK INTL,< 1000 ft,942,None,6/23/03 0:00,No damage,COMAIR AIRLINES,Virginia,Approach,Small,No Cloud,European starling,N,50

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25558 entries, 0 to 25557
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Airport: Name                       25429 non-null  object
 1   Altitude bin                        25429 non-null  object
 2   Wildlife: Number Struck Actual      25558 non-null  int64
 3   Effect: Impact to flight            25429 non-null  object
 4   FlightDate                          25429 non-null  object
 5   Effect: Indicated Damage            25558 non-null  object
 6   Aircraft: Airline/Operator          25429 non-null  object
 7   Origin State                        25109 non-null  object
 8   When: Phase of flight               25429 non-null  object
 9   Wildlife: Size                      25429 non-null  object
 10  Conditions: Sky                     25558 non-null  object
 11  Wildlife: Species                   25558 non-null  object
 12  Pilot warned of birds or wildlife?  25429 non-null  object
 13  Feet above ground                   25429 non-null  object
dtypes: int64(1), object(13)
memory usage: 2.7+ MB

In [16]:
df1.isnull().sum()

Airport: Name                         129
Altitude bin                          129
Wildlife: Number Struck Actual          0
Effect: Impact to flight              129
FlightDate                            129
Effect: Indicated Damage                0
Aircraft: Airline/Operator            129
Origin State                          449
When: Phase of flight                 129
Wildlife: Size                        129
Conditions: Sky                         0
Wildlife: Species                       0
Pilot warned of birds or wildlife?    129
Feet above ground                     129
dtype: int64

In [18]:
df1.to_csv('Bird_strike_df1.csv') # saving in csv

In [3]:
df2 = pd.read_csv('Bird_strike_df1.csv')

In [4]:
df2.head()

,Airport: Name,Altitude bin(>1000),Wildlife: Number Struck Actual,Effect: Impact to flight,FlightDate,Effect: Indicated Damage,Aircraft: Airline/Operator,Origin State,When: Phase of flight,Wildlife: Size,Conditions: Sky,Wildlife: Species,Pilot warned of birds or wildlife?,Feet above ground
0,LAGUARDIA NY,1.0,859,Engine Shut Down,01-01-2000,Caused damage,US AIRWAYS*,New York,Climb,Medium,No Cloud,Unknown bird - medium,0.0,1500.0
1,DALLAS/FORT WORTH INTL ARPT,0.0,424,None,01-01-2001,Caused damage,AMERICAN AIRLINES,Texas,Landing Roll,Small,Some Cloud,Rock pigeon,1.0,0.0
2,LAKEFRONT AIRPORT,0.0,261,None,01-01-2001,No damage,BUSINESS,Louisiana,Approach,Small,No Cloud,European starling,0.0,50.0
3,SEATTLE-TACOMA INTL,0.0,806,Precautionary Landing,01-01-2002,No damage,ALASKA AIRLINES,Washington,Climb,Small,Some Cloud,European starling,1.0,50.0
4,NORFOLK INTL,0.0,942,None,01-01-2003,No damage,COMAIR AIRLINES,Virginia,Approach,Small,No Cloud,European starling,0.0,50.0

In [5]:
df2.isnull().sum()

Airport: Name                         129
Altitude bin(>1000)                   129
Wildlife: Number Struck Actual          0
Effect: Impact to flight              129
FlightDate                            129
Effect: Indicated Damage                0
Aircraft: Airline/Operator            129
Origin State                          449
When: Phase of flight                 129
Wildlife: Size                        129
Conditions: Sky                         0
Wildlife: Species                       0
Pilot warned of birds or wildlife?    129
Feet above ground                     129
dtype: int64

# Handling Missing Values:

In [6]:
df2 = df2.fillna({'Airport: Name': df2['Airport: Name'].mode()[0]})

In [8]:
df2 = df2.fillna({'Altitude bin(>1000)': df2['Altitude bin(>1000)'].median()})

In [10]:
df2 = df2.fillna({'Effect: Impact to flight': df2['Effect: Impact to flight'].mode()[0]})

In [12]:
df2 = df2.fillna({'FlightDate': df2['FlightDate'].mode()[0]})

In [13]:
df2 = df2.fillna({'Aircraft: Airline/Operator': df2['Aircraft: Airline/Operator'].mode()[0]})

In [14]:
df2 = df2.fillna({'Origin State': df2['Origin State'].mode()[0]})

In [15]:
df2 = df2.fillna({'When: Phase of flight': df2['When: Phase of flight'].mode()[0]})

In [16]:
df2 = df2.fillna({'Pilot warned of birds or wildlife?': df2['Pilot warned of birds or wildlife?'].mode()[0]})

In [18]:
df2 = df2.fillna({'Wildlife: Size': df2['Wildlife: Size'].mode()[0]})

In [19]:
df2 = df2.fillna({'Feet above ground': df2['Feet above ground'].mean()})

In [20]:
df2.isnull().sum()

Airport: Name                         0
Altitude bin(>1000)                   0
Wildlife: Number Struck Actual        0
Effect: Impact to flight              0
FlightDate                            0
Effect: Indicated Damage              0
Aircraft: Airline/Operator            0
Origin State                          0
When: Phase of flight                 0
Wildlife: Size                        0
Conditions: Sky                       0
Wildlife: Species                     0
Pilot warned of birds or wildlife?    0
Feet above ground                     0
dtype: int64

In [22]:
df2.to_csv('Bird_strike_df2.csv') # saving in csv